package completePrinter;

public class AutoGeneratedLambdaMessage {

	String fatherMethod;
	String descriptor;
	String descriptorInterface;
	String interfaceName;
	int line;

	public void setFatherMethod(String fatherMethod) {
		this.fatherMethod = fatherMethod;
	}

	public void setDescriptor(String descriptor) {
		this.descriptor = descriptor;
	}

	public void setDescriptorInterface(String descriptorInterface) {
		this.descriptorInterface = descriptorInterface;
	}

	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}

	public void setLine(int line) {
		this.line = line;
	}

	@Override
	public String toString() {
		return "AutoGeneratedLambdaMessage [fatherMethod=" + fatherMethod + ", descriptor=" + descriptor
				+ ", descriptorInterface=" + descriptorInterface + ", interfaceName=" + interfaceName + ", line=" + line
				+ "]";
	}

}
