package projet;

public class AutoGeneratedLambdaMessage {

	private String source;
	private String fatherMethod;
	private String descriptor;
	private String descriptorInterface;
	private String interfaceName;
	private int line;
	private String capture = "";

	public void setFatherMethod(String fatherMethod) {
		this.fatherMethod = fatherMethod;
	}
	

	public void setDescriptor(String descriptor) {
		this.descriptor = descriptor;
	}

	public void setDescriptorInterface(String descriptorInterface) {
		this.descriptorInterface = descriptorInterface;
	}

	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public void setLine(int line) {
		this.line = line;
	}
	
	public void generateCapture() {
		int sizeDescriptor = descriptor.length();
		int sizeInterfaceDescriptor = descriptorInterface.length();
		if(sizeDescriptor > sizeInterfaceDescriptor )
			capture = descriptor.substring(sizeInterfaceDescriptor,sizeDescriptor);
	}

	@Override
	public String toString() {
		StringBuilder m = new StringBuilder();
		m.append("AutoGeneratedLambdaMessage [source=" + source + ", fatherMethod=" + fatherMethod + ", descriptor="
				+ descriptor + ", descriptorInterface=" + descriptorInterface + ", interfaceName=" + interfaceName
				+ ", line=");

		if (line == 0)
			m.append("missed");
		else
			m.append(line);

		m.append(", capture=" + capture +" ]");

		return m.toString();
	}
}
