package projet;

import java.io.IOException;
import java.util.ArrayList;

import org.objectweb.asm.ClassReader;

public class Main {

	public static void main(String[] args) throws IOException {
		GreatPrinter printer = new GreatPrinter();
		ClassReader reader = new ClassReader("projet/TestLambda");
		reader.accept(printer, 0);
		
		ArrayList<AutoGeneratedLambdaMessage> methods = printer.getLambda();
		ArrayList<MessageMethod> lambda = printer.getMethods();
		
		methods.forEach(x -> System.out.println(x));
		lambda.forEach(x -> System.out.println(x));
	}

}
